# Generated by Django 3.0.2 on 2020-02-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0005_auto_20200218_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='genre',
            new_name='genres',
        ),
    ]
