# Generated by Django 3.0.2 on 2020-02-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0010_auto_20200221_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedwork',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
