# Generated by Django 3.0.2 on 2020-02-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0013_rentedwork_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedwork',
            name='returned',
        ),
    ]
