# Generated by Django 3.0.2 on 2020-03-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0021_rating_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
