# Generated by Django 3.0.2 on 2020-03-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0024_auto_20200306_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='use_display_name',
            field=models.BooleanField(default=False),
        ),
    ]
