# Generated by Django 3.0.2 on 2020-03-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0027_auto_20200306_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
