# Generated by Django 3.0.2 on 2020-03-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0032_work_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date_added',
            field=models.DateField(),
        ),
    ]
