# Generated by Django 3.0.2 on 2020-02-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creator_Work',
        ),
    ]
