# Generated by Django 3.0.2 on 2020-02-18 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0002_delete_creator_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.Creator')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.Type')),
            ],
        ),
    ]
