# Generated by Django 3.0.2 on 2020-02-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0003_creatorwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='creators',
            field=models.ManyToManyField(to='rental_system.Creator'),
        ),
        migrations.DeleteModel(
            name='CreatorWork',
        ),
    ]
