# Generated by Django 3.0.2 on 2020-02-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0004_auto_20200218_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='genre',
            field=models.ManyToManyField(to='rental_system.Genre'),
        ),
    ]
