# Generated by Django 3.0.2 on 2020-02-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0006_auto_20200218_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='publishers',
            field=models.ManyToManyField(to='rental_system.Publisher'),
        ),
    ]
