# Generated by Django 3.0.2 on 2020-02-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0007_auto_20200219_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='pub_date',
            field=models.IntegerField(),
        ),
    ]
