# Generated by Django 3.0.2 on 2020-02-21 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_system', '0008_auto_20200219_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField()),
                ('rented_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
