# Generated by Django 3.0.2 on 2020-02-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0011_rentedwork_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedwork',
            name='returned',
        ),
    ]
