# Generated by Django 3.0.2 on 2020-02-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0014_remove_rentedwork_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedwork',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
