# Generated by Django 3.0.2 on 2020-02-27 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0015_rentedwork_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentedwork',
            name='rented_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_system.Work'),
        ),
    ]
