# Generated by Django 3.0.2 on 2020-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0016_auto_20200228_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentedwork',
            name='date_returned',
            field=models.DateTimeField(null=True),
        ),
    ]
