# Generated by Django 3.0.2 on 2020-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0018_auto_20200305_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
