# Generated by Django 3.0.2 on 2020-03-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0020_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
