# Generated by Django 3.0.2 on 2020-03-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0022_rating_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
