# Generated by Django 3.0.2 on 2020-03-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0023_auto_20200306_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='display_name',
            field=models.CharField(default='Display name', max_length=200),
        ),
        migrations.AlterField(
            model_name='creator',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
