# Generated by Django 3.0.2 on 2020-03-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0025_creator_use_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='publishers',
            field=models.ManyToManyField(null=True, to='rental_system.Publisher'),
        ),
    ]
