# Generated by Django 3.0.2 on 2020-03-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0026_auto_20200306_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='publishers',
            field=models.ManyToManyField(blank=True, null=True, to='rental_system.Publisher'),
        ),
    ]
