# Generated by Django 3.0.2 on 2020-03-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0028_rating_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='trailer',
            field=models.URLField(blank=True),
        ),
    ]
