# Generated by Django 3.0.2 on 2020-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0029_work_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
