# Generated by Django 3.0.2 on 2020-03-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0030_work_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='publishers',
            field=models.ManyToManyField(blank=True, to='rental_system.Publisher'),
        ),
    ]
