# Generated by Django 3.0.2 on 2020-03-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_system', '0033_auto_20200310_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
